name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx vitest --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Install jq and bc
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc

      - name: Check Coverage > 50%
        run: |
          THRESHOLD=50
          LINES_PCT=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          FUNCTIONS_PCT=$(jq '.total.functions.pct' coverage/coverage-summary.json)
          STATEMENTS_PCT=$(jq '.total.statements.pct' coverage/coverage-summary.json)
          BRANCHES_PCT=$(jq '.total.branches.pct' coverage/coverage-summary.json)

          echo "Lines coverage: $LINES_PCT%"
          echo "Functions coverage: $FUNCTIONS_PCT%"
          echo "Statements coverage: $STATEMENTS_PCT%"
          echo "Branches coverage: $BRANCHES_PCT%"

          if (( $(echo "$LINES_PCT < $THRESHOLD" | bc -l) )) || \
             (( $(echo "$FUNCTIONS_PCT < $THRESHOLD" | bc -l) )) || \
             (( $(echo "$STATEMENTS_PCT < $THRESHOLD" | bc -l) )) || \
             (( $(echo "$BRANCHES_PCT < $THRESHOLD" | bc -l) )); then
            echo "Coverage is below ${THRESHOLD}%!"
            exit 1
          else
            echo "Coverage is above ${THRESHOLD}%!"
          fi
